### ISSUE TITLE
No https / SSL?

### ISSUE THREAD

**Issue by pjv** [ishani/xSyn#1]

**Comment by ishani** [comment]
Fair point! I've only been running this in Azure under their https wrapping for app services so didn't really need it - but I'll drop in a path to use RunTLS() with certificate options .. and check out the LetsEncrypt support Gin has too.

**Comment by ishani** [comment]
on latest you have options for both using your own keys to enable TLS or to use Let's Encrypt. I've tested the automatic Let's Encrypt stuff on AWS and it works a treat; haven't tested the manual keys yet but it's very standard Gin code so it should work. Check the latest config file for details.
